import { Case, Round } from '../types';

/**
 * UTILITIES FOR EXPORTING AND PRINTING CASE FILES
 */

const sanitizeFilename = (title: string): string => {
    return title.replace(/[^a-z0-9]/gi, '_').replace(/_{2,}/g, '_').toUpperCase();
};

const formatDate = (dateString: string): string => {
    return new Date(dateString).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric'
    });
};

export const exportService = {
    /**
     * Generates and triggers a download of a Markdown file
     */
    downloadMarkdown: (activeCase: Case, rounds: Round[]) => {
        let md = `# CASE FILE: ${activeCase.title}\n`;
        md += `**Ref ID:** ${activeCase.id.split('-')[0].toUpperCase()}\n`;
        md += `**Adversary:** ${activeCase.opponentType}\n`;
        md += `**Date Created:** ${formatDate(activeCase.createdAt)}\n`;
        md += `**Status:** ${activeCase.isClosed ? 'Closed' : 'Active'}\n`;
        md += `**Context:** ${activeCase.note || "N/A"}\n\n`;
        md += `---\n\n`;

        rounds.forEach(r => {
            md += `## ROUND ${r.roundNumber} - ${new Date(r.createdAt).toLocaleString()}\n\n`;
            const sender = r.senderIdentity ? r.senderIdentity : "Adversary";
            
            md += `### 1. Evidence (From: ${sender})\n`;
            md += `> ${r.opponentText.replace(/\n/g, '\n> ')}\n\n`;

            if (r.isAnalyzed) {
                md += `### 2. Analysis\n`;
                md += `- **Vibe:** ${r.vibeCheck}\n`;
                md += `- **Legal Risk:** ${r.legalRiskScore}/100\n`;
                if (r.confidenceScore !== undefined) {
                    md += `- **AI Confidence:** ${r.confidenceScore}% (${r.confidenceExplanation})\n`;
                }
                md += `- **Tactics Detected:** ${r.detectedFallacies?.join(', ') || "None"}\n\n`;

                md += `### 3. Drafted Response (${r.selectedMode})\n`;
                const responseKey = r.selectedMode === 'Peacekeeper' ? 'soft' : r.selectedMode === 'Barrister' ? 'firm' : r.selectedMode === 'Grey Rock' ? 'greyRock' : 'nuclear';
                const response = r.responses[responseKey as keyof typeof r.responses];
                md += `\`\`\`text\n${response || "(No draft generated)"}\n\`\`\`\n\n`;
                
                if (r.expertInsights) {
                     md += `> **Expert Insight:** ${r.expertInsights}\n\n`;
                }
            }
            md += `---\n\n`;
        });

        md += `\n*Generated by ConflictResolution.ai*`;

        const filename = `CASE_${sanitizeFilename(activeCase.title)}_${new Date().toISOString().split('T')[0]}.md`;
        const blob = new Blob([md], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    },

    /**
     * Triggers the browser print dialog with a formatted HTML view.
     * Users can choose "Save as PDF" from the print dialog.
     */
    printToPDF: (activeCase: Case, rounds: Round[]) => {
        // 1. Create invisible iframe
        const iframe = document.createElement('iframe');
        iframe.style.position = 'fixed';
        iframe.style.top = '0';
        iframe.style.left = '0';
        iframe.style.width = '1px';
        iframe.style.height = '1px';
        iframe.style.opacity = '0';
        iframe.style.pointerEvents = 'none';
        iframe.style.zIndex = '99999';
        document.body.appendChild(iframe);

        const doc = iframe.contentWindow?.document;
        if (!doc) return;

        // 2. Generate Print-Optimized HTML
        const content = `
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <title>CASE FILE: ${activeCase.title}</title>
                <style>
                    @page { size: A4; margin: 20mm; }
                    body { 
                        font-family: 'Times New Roman', serif; 
                        padding: 0; 
                        margin: 0;
                        color: #000; 
                        line-height: 1.5; 
                        background: white;
                    }
                    .container { max-width: 100%; }
                    h1 { font-size: 24px; text-transform: uppercase; border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 20px; letter-spacing: 1px; }
                    .header { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 40px; }
                    .meta p { margin: 4px 0; font-size: 14px; color: #333; }
                    .badge { border: 2px solid #000; padding: 5px 15px; font-weight: bold; text-transform: uppercase; font-size: 14px; letter-spacing: 1px; }
                    
                    .section { margin-bottom: 30px; page-break-inside: avoid; }
                    
                    .context-box { background: #f9f9f9; padding: 20px; border: 1px solid #ddd; margin-bottom: 30px; font-style: italic; border-radius: 4px; }
                    
                    .round { border-left: 4px solid #ccc; padding-left: 20px; margin-bottom: 40px; }
                    .round-header { display: flex; align-items: center; gap: 10px; margin-bottom: 15px; }
                    .round-badge { background: #000; color: #fff; padding: 3px 8px; font-size: 11px; font-weight: bold; border-radius: 2px; text-transform: uppercase; }
                    .timestamp { color: #666; font-size: 12px; }
                    
                    .label { font-size: 10px; font-weight: bold; text-transform: uppercase; color: #666; margin-bottom: 5px; display: block; letter-spacing: 0.5px; }
                    .text-box { background: #f0f0f0; padding: 15px; border: 1px solid #ddd; font-family: monospace; font-size: 12px; white-space: pre-wrap; margin-bottom: 15px; border-radius: 4px; }
                    
                    .analysis-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 15px; }
                    .analysis-box { background: #fff; }
                    
                    .response-box { border: 1px solid #ccc; padding: 15px; font-size: 14px; background: #fff; border-radius: 4px; font-family: serif; }
                    
                    .footer { text-align: center; font-size: 10px; color: #999; margin-top: 50px; border-top: 1px solid #eee; padding-top: 15px; }
                    
                    @media print {
                        body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <div class="meta">
                            <h1>Confidential Case File</h1>
                            <p><strong>Ref ID:</strong> ${activeCase.id.split('-')[0].toUpperCase()}</p>
                            <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
                            <p><strong>Subject:</strong> ${activeCase.title}</p>
                        </div>
                        <div>
                            <div class="badge">${activeCase.opponentType}</div>
                        </div>
                    </div>

                    <div class="context-box">
                        <span class="label">Initial Context</span>
                        ${activeCase.note || "No context provided."}
                    </div>

                    ${rounds.map(r => {
                        const responseKey = r.selectedMode === 'Peacekeeper' ? 'soft' : r.selectedMode === 'Barrister' ? 'firm' : r.selectedMode === 'Grey Rock' ? 'greyRock' : 'nuclear';
                        const responseText = r.responses[responseKey as keyof typeof r.responses] || "(No response generated)";
                        
                        // Sanitize text for HTML display
                        const safeOpponentText = r.opponentText.replace(/</g, "&lt;").replace(/>/g, "&gt;");
                        const safeResponseText = responseText.replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\n/g, '<br/>');

                        return `
                            <div class="section round">
                                <div class="round-header">
                                    <span class="round-badge">ROUND ${r.roundNumber}</span>
                                    <span class="timestamp">${new Date(r.createdAt).toLocaleString()}</span>
                                </div>
                                
                                <div style="margin-bottom: 20px;">
                                    <span class="label">Incoming Transmission (${r.senderIdentity || "Adversary"})</span>
                                    <div class="text-box">"${safeOpponentText}"</div>
                                </div>

                                <div class="analysis-grid">
                                    <div class="analysis-box">
                                        <span class="label">Psychological Profile</span>
                                        <p style="margin:0; font-size:13px; margin-top:4px;">${r.vibeCheck}</p>
                                    </div>
                                    <div class="analysis-box">
                                        <span class="label">Tactical Assessment</span>
                                        <p style="margin:0; font-size:13px; margin-top:4px;">
                                            Risk Score: ${r.legalRiskScore}/100<br/>
                                            Tactics: ${r.detectedFallacies?.join(', ') || "None"}
                                        </p>
                                    </div>
                                </div>

                                <div>
                                    <span class="label">Strategic Response (${r.selectedMode})</span>
                                    <div class="response-box">${safeResponseText}</div>
                                </div>
                            </div>
                        `;
                    }).join('')}

                    <div class="footer">Generated by ConflictResolution.ai — Strictly Confidential</div>
                </div>
            </body>
            </html>
        `;

        // 3. Write and Print
        doc.open();
        doc.write(content);
        doc.close();

        // Use a timeout to ensure styles load and browser is ready
        setTimeout(() => {
            iframe.contentWindow?.focus();
            iframe.contentWindow?.print();
            
            // Cleanup iframe after a delay to allow print dialog to handle the content
            setTimeout(() => {
                document.body.removeChild(iframe);
            }, 1000);
        }, 200);
    }
};