import { Case, Round } from '../types';

/**
 * UTILITIES FOR EXPORTING AND PRINTING CASE FILES
 */

const sanitizeFilename = (title: string): string => {
    return title.replace(/[^a-z0-9]/gi, '_').replace(/_{2,}/g, '_').toUpperCase();
};

const formatDate = (dateString: string): string => {
    return new Date(dateString).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric'
    });
};

export const exportService = {
    /**
     * Generates and triggers a download of a Markdown file
     */
    downloadMarkdown: (activeCase: Case, rounds: Round[]) => {
        let md = `# CASE FILE: ${activeCase.title}\n`;
        md += `**Ref ID:** ${activeCase.id.split('-')[0].toUpperCase()}\n`;
        md += `**Adversary:** ${activeCase.opponentType}\n`;
        md += `**Date Created:** ${formatDate(activeCase.createdAt)}\n`;
        md += `**Status:** ${activeCase.isClosed ? 'Closed' : 'Active'}\n`;
        md += `**Context:** ${activeCase.note || "N/A"}\n\n`;
        md += `---\n\n`;

        rounds.forEach(r => {
            md += `## ROUND ${r.roundNumber} - ${new Date(r.createdAt).toLocaleString()}\n\n`;
            const sender = r.senderIdentity ? r.senderIdentity : "Adversary";
            
            md += `### 1. Evidence (From: ${sender})\n`;
            md += `> ${r.opponentText.replace(/\n/g, '\n> ')}\n\n`;

            if (r.isAnalyzed) {
                md += `### 2. Analysis\n`;
                md += `- **Vibe:** ${r.vibeCheck}\n`;
                md += `- **Legal Risk:** ${r.legalRiskScore}/100\n`;
                if (r.confidenceScore !== undefined) {
                    md += `- **AI Confidence:** ${r.confidenceScore}% (${r.confidenceExplanation})\n`;
                }
                md += `- **Tactics Detected:** ${r.detectedFallacies?.join(', ') || "None"}\n\n`;

                md += `### 3. Drafted Response (${r.selectedMode})\n`;
                const responseKey = r.selectedMode === 'Peacekeeper' ? 'soft' : r.selectedMode === 'Barrister' ? 'firm' : r.selectedMode === 'Grey Rock' ? 'greyRock' : 'nuclear';
                const response = r.responses[responseKey as keyof typeof r.responses];
                md += `\`\`\`text\n${response || "(No draft generated)"}\n\`\`\`\n\n`;
                
                if (r.expertInsights) {
                     md += `> **Expert Insight:** ${r.expertInsights}\n\n`;
                }
            }
            md += `---\n\n`;
        });

        md += `\n*Generated by ConflictResolution.ai*`;

        const filename = `CASE_${sanitizeFilename(activeCase.title)}_${new Date().toISOString().split('T')[0]}.md`;
        const blob = new Blob([md], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    },

    /**
     * Triggers the browser print dialog with a formatted HTML view.
     * Users can choose "Save as PDF" from the print dialog.
     */
    printToPDF: (activeCase: Case, rounds: Round[]) => {
        const existingOverlay = document.getElementById('cr-print-overlay');
        if (existingOverlay) {
            existingOverlay.remove();
        }

        const content = `
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <title>CASE FILE: ${activeCase.title}</title>
                <style>
                    @page { size: A4; margin: 20mm; }
                    body { 
                        font-family: 'Times New Roman', serif; 
                        padding: 0; 
                        margin: 0;
                        color: #000; 
                        line-height: 1.5; 
                        background: white;
                    }
                    .container { max-width: 100%; }
                    h1 { font-size: 24px; text-transform: uppercase; border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 20px; letter-spacing: 1px; }
                    .header { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 40px; }
                    .meta p { margin: 4px 0; font-size: 14px; color: #333; }
                    .badge { border: 2px solid #000; padding: 5px 15px; font-weight: bold; text-transform: uppercase; font-size: 14px; letter-spacing: 1px; }
                    
                    .section { margin-bottom: 30px; page-break-inside: avoid; }
                    
                    .context-box { background: #f9f9f9; padding: 20px; border: 1px solid #ddd; margin-bottom: 30px; font-style: italic; border-radius: 4px; }
                    
                    .round { border-left: 4px solid #ccc; padding-left: 20px; margin-bottom: 40px; }
                    .round-header { display: flex; align-items: center; gap: 10px; margin-bottom: 15px; }
                    .round-badge { background: #000; color: #fff; padding: 3px 8px; font-size: 11px; font-weight: bold; border-radius: 2px; text-transform: uppercase; }
                    .timestamp { color: #666; font-size: 12px; }
                    
                    .label { font-size: 10px; font-weight: bold; text-transform: uppercase; color: #666; margin-bottom: 5px; display: block; letter-spacing: 0.5px; }
                    .text-box { background: #f0f0f0; padding: 15px; border: 1px solid #ddd; font-family: monospace; font-size: 12px; white-space: pre-wrap; margin-bottom: 15px; border-radius: 4px; }
                    
                    .analysis-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 15px; }
                    .analysis-box { background: #fff; }
                    
                    .response-box { border: 1px solid #ccc; padding: 15px; font-size: 14px; background: #fff; border-radius: 4px; font-family: serif; }
                    
                    .footer { text-align: center; font-size: 10px; color: #999; margin-top: 50px; border-top: 1px solid #eee; padding-top: 15px; }
                    
                    @media print {
                        body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <div class="meta">
                            <h1>Confidential Case File</h1>
                            <p><strong>Ref ID:</strong> ${activeCase.id.split('-')[0].toUpperCase()}</p>
                            <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
                            <p><strong>Subject:</strong> ${activeCase.title}</p>
                        </div>
                        <div>
                            <div class="badge">${activeCase.opponentType}</div>
                        </div>
                    </div>

                    <div class="context-box">
                        <span class="label">Initial Context</span>
                        ${activeCase.note || "No context provided."}
                    </div>

                    ${rounds.map(r => {
                        const responseKey = r.selectedMode === 'Peacekeeper' ? 'soft' : r.selectedMode === 'Barrister' ? 'firm' : r.selectedMode === 'Grey Rock' ? 'greyRock' : 'nuclear';
                        const responseText = r.responses[responseKey as keyof typeof r.responses] || "(No response generated)";
                        
                        // Sanitize text for HTML display
                        const safeOpponentText = r.opponentText.replace(/</g, "&lt;").replace(/>/g, "&gt;");
                        const safeResponseText = responseText.replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\n/g, '<br/>');

                        return `
                            <div class="section round">
                                <div class="round-header">
                                    <span class="round-badge">ROUND ${r.roundNumber}</span>
                                    <span class="timestamp">${new Date(r.createdAt).toLocaleString()}</span>
                                </div>
                                
                                <div style="margin-bottom: 20px;">
                                    <span class="label">Incoming Transmission (${r.senderIdentity || "Adversary"})</span>
                                    <div class="text-box">"${safeOpponentText}"</div>
                                </div>

                                <div class="analysis-grid">
                                    <div class="analysis-box">
                                        <span class="label">Psychological Profile</span>
                                        <p style="margin:0; font-size:13px; margin-top:4px;">${r.vibeCheck}</p>
                                    </div>
                                    <div class="analysis-box">
                                        <span class="label">Tactical Assessment</span>
                                        <p style="margin:0; font-size:13px; margin-top:4px;">
                                            Risk Score: ${r.legalRiskScore}/100<br/>
                                            Tactics: ${r.detectedFallacies?.join(', ') || "None"}
                                        </p>
                                    </div>
                                </div>

                                <div>
                                    <span class="label">Strategic Response (${r.selectedMode})</span>
                                    <div class="response-box">${safeResponseText}</div>
                                </div>
                            </div>
                        `;
                    }).join('')}

                    <div class="footer">Generated by ConflictResolution.ai — Strictly Confidential</div>
                </div>
            </body>
            </html>
        `;

        // Build an in-app modal so the print dialog doesn't steal the tab.
        const overlay = document.createElement('div');
        overlay.id = 'cr-print-overlay';
        overlay.style.position = 'fixed';
        overlay.style.inset = '0';
        overlay.style.background = 'rgba(2, 6, 23, 0.75)';
        overlay.style.backdropFilter = 'blur(6px)';
        overlay.style.zIndex = '100000';
        overlay.style.display = 'flex';
        overlay.style.alignItems = 'center';
        overlay.style.justifyContent = 'center';
        overlay.style.padding = '24px';

        const modal = document.createElement('div');
        modal.style.width = 'min(1100px, 96vw)';
        modal.style.height = 'min(90vh, 900px)';
        modal.style.background = '#0b1220';
        modal.style.border = '1px solid rgba(148, 163, 184, 0.2)';
        modal.style.borderRadius = '16px';
        modal.style.boxShadow = '0 20px 60px rgba(0, 0, 0, 0.45)';
        modal.style.display = 'flex';
        modal.style.flexDirection = 'column';
        modal.style.overflow = 'hidden';

        const header = document.createElement('div');
        header.style.display = 'flex';
        header.style.alignItems = 'center';
        header.style.justifyContent = 'space-between';
        header.style.padding = '14px 18px';
        header.style.borderBottom = '1px solid rgba(148, 163, 184, 0.2)';
        header.style.color = '#e2e8f0';
        header.style.fontSize = '14px';
        header.style.fontWeight = '600';

        const title = document.createElement('div');
        title.textContent = 'Print / Save PDF';

        const actions = document.createElement('div');
        actions.style.display = 'flex';
        actions.style.gap = '8px';

        const printButton = document.createElement('button');
        printButton.type = 'button';
        printButton.textContent = 'Open Print Dialog';
        printButton.style.background = '#2563eb';
        printButton.style.border = 'none';
        printButton.style.color = '#fff';
        printButton.style.padding = '8px 12px';
        printButton.style.borderRadius = '8px';
        printButton.style.cursor = 'pointer';
        printButton.style.fontSize = '12px';
        printButton.style.fontWeight = '600';

        const closeButton = document.createElement('button');
        closeButton.type = 'button';
        closeButton.textContent = 'Close';
        closeButton.style.background = 'transparent';
        closeButton.style.border = '1px solid rgba(148, 163, 184, 0.4)';
        closeButton.style.color = '#e2e8f0';
        closeButton.style.padding = '8px 12px';
        closeButton.style.borderRadius = '8px';
        closeButton.style.cursor = 'pointer';
        closeButton.style.fontSize = '12px';
        closeButton.style.fontWeight = '600';

        actions.appendChild(printButton);
        actions.appendChild(closeButton);
        header.appendChild(title);
        header.appendChild(actions);

        const hint = document.createElement('div');
        hint.textContent = 'Use the print dialog to Save as PDF. This preview will stay open.';
        hint.style.padding = '10px 18px';
        hint.style.fontSize = '12px';
        hint.style.color = '#94a3b8';
        hint.style.borderBottom = '1px solid rgba(148, 163, 184, 0.2)';

        const body = document.createElement('div');
        body.style.flex = '1';
        body.style.background = '#0f172a';
        body.style.padding = '16px';

        const iframe = document.createElement('iframe');
        iframe.title = 'Case file print preview';
        iframe.style.width = '100%';
        iframe.style.height = '100%';
        iframe.style.border = 'none';
        iframe.style.borderRadius = '10px';
        iframe.style.background = '#fff';

        body.appendChild(iframe);
        modal.appendChild(header);
        modal.appendChild(hint);
        modal.appendChild(body);
        overlay.appendChild(modal);
        document.body.appendChild(overlay);

        const handleKey = (event: KeyboardEvent) => {
            if (event.key === 'Escape') cleanup();
        };

        const cleanup = () => {
            window.removeEventListener('keydown', handleKey);
            overlay.remove();
        };

        window.addEventListener('keydown', handleKey);

        closeButton.onclick = cleanup;
        printButton.onclick = () => {
            iframe.contentWindow?.focus();
            iframe.contentWindow?.print();
        };

        const doc = iframe.contentWindow?.document;
        if (!doc) {
            cleanup();
            return;
        }

        doc.open();
        doc.write(content);
        doc.close();
    }
};
