import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI, HarmCategory, HarmBlockThreshold } from "@google/genai";

export const runtime = "nodejs";

export async function POST(request: NextRequest) {
  if (!process.env.API_KEY) {
    return NextResponse.json({ error: "Server configuration error" }, { status: 500 });
  }

  let body: any;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON payload" }, { status: 400 });
  }

  const {
    opponentType,
    contextSummary,
    historyText,
    currentText,
    planType,
    useDeepThinking,
    senderIdentity,
  } = body || {};

  const MAX_INPUT_CHARS = 15000;
  const BUSINESS_OUTPUT_LIMIT = 2000;
  const truncatedText = (currentText || "").slice(0, MAX_INPUT_CHARS);

  const SYSTEM_INSTRUCTION = `
You are Conflict Resolution AI.
You are NOT a lawyer.

**TASK**
Analyze the input and generate 4 strategic response drafts.

**RESPONSE FORMATTING STANDARDS:**
1. **Structure:** Use clear, distinct paragraphs separated by "\\n\\n".
2. **Lists:** Use **bullet points** ("- ") for any lists, steps, or multiple options within a response.
3. **Legal/Contractual Text:** You MUST use **code blocks** (\`\`\`) to wrap any specific legal clauses, proposed contract amendments, or formal citations.
4. **Emphasis:** Use asterisks for **bold** text on key terms.

**CRITICAL JSON FORMATTING RULES:**
1. Output MUST be valid JSON.
2. Do NOT use newlines/line-breaks inside string values. Replace all newlines with a single space or literal "\\n".
3. Do NOT include markdown formatting (like \`\`\`json). Just the raw JSON object.
4. Do NOT use double quotes (") inside string values. Use single quotes (') instead. This is critical for parsing.
5. Keep the total character count concise.

**MODES:**
1. PEACEKEEPER: De-escalate.
2. BARRISTER: Factual, cool, detached. Use code blocks for specific demands or legal citations.
3. GREY ROCK: Boring, short, no emotion. No J.A.D.E. (Justify, Argue, Defend, Explain).
4. NUCLEAR: Witty, assertive, exposes behavior. Savage but legal.
`;

  const ANALYSIS_SCHEMA = `
{
  "vibeCheck": "string - 1 sentence emotional analysis.",
  "confidenceScore": 0,
  "confidenceExplanation": "string - short reason.",
  "legalRiskScore": 0,
  "legalRiskExplanation": "string - short explanation.",
  "detectedFallacies": ["string"],
  "analysisSummary": "string - concise summary of their key points.",
  "responses": {
    "soft": "string - Peacekeeper draft",
    "firm": "string - Barrister draft",
    "nuclear": "string - Nuclear draft",
    "greyRock": "string - Grey Rock draft"
  }
}
`;

  const prompt = `
    **CONTEXT:**
    Adversary: ${opponentType}
    Note: ${contextSummary}

    **HISTORY:**
    ${historyText ? historyText : "(None)"}

    **LATEST MESSAGE (Analyze This):**
    ${senderIdentity ? `From: ${senderIdentity}` : ""}
    "${truncatedText}"

    Return JSON matching this schema:
    ${ANALYSIS_SCHEMA}
  `;

  const modelName = planType === "premium" ? "gemini-3-pro-preview" : "gemini-3-flash-preview";

  let maxOutputTokens = BUSINESS_OUTPUT_LIMIT;
  let thinkingBudget = 0;

  if (planType === "premium" && useDeepThinking) {
    thinkingBudget = 2048;
    maxOutputTokens = thinkingBudget + BUSINESS_OUTPUT_LIMIT;
  }

  const config = {
    systemInstruction: SYSTEM_INSTRUCTION,
    responseMimeType: "application/json",
    temperature: 0.7,
    maxOutputTokens,
    safetySettings: [
      { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_NONE },
      { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_NONE },
      { category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, threshold: HarmBlockThreshold.BLOCK_NONE },
      { category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_NONE },
    ],
    ...(thinkingBudget > 0 ? { thinkingConfig: { thinkingBudget } } : {}),
  };

  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateContent({
      model: modelName,
      contents: prompt,
      config,
    });

    const text = response.text;
    if (!text) throw new Error("No text generated by AI.");

    let jsonString = text.trim();
    jsonString = jsonString.replace(/^```json\s*/i, "").replace(/^```\s*/i, "").replace(/\s*```$/i, "");

    const firstOpen = jsonString.indexOf("{");
    const lastClose = jsonString.lastIndexOf("}");
    if (firstOpen !== -1 && lastClose !== -1 && lastClose > firstOpen) {
      jsonString = jsonString.substring(firstOpen, lastClose + 1);
    }

    jsonString = jsonString.replace(/[\n\r]+/g, " ");

    const parsed = JSON.parse(jsonString);
    return NextResponse.json(parsed);
  } catch (error: any) {
    return NextResponse.json(
      { error: "AI Generation Failed", details: error?.message || "Unknown error" },
      { status: 500 }
    );
  }
}
